### ISSUE TITLE
Add support for boost::signals

### ISSUE THREAD

**Issue by eldruin** [hmeine/geomap#11]
At the moment this library uses with sigc++ for signals. However, an implementation using boost signals would also be interesting.
My current plan is:
- [ ] Add cmake option to select sigc++ or boost signals (maybe non exclusive?)
- [ ] Add switches to use boost signals or sigc++ across all code (non-exclusivity would be an important decision for this)

I am working on this [here](https://github.com/eldruin/geomap/tree/signals).

**Comment by hmeine** [comment]
We did this in the past! The code was less elegant, so it may not be in master anymore, but the branch should still exist somewhere.

**Comment by eldruin** [comment]
The branch looks good. Thanks!
Do you want to keep both implementations or did you intend to port it to `boost_signals` only?

**Comment by hmeine** [comment]
Back then I found the sigc++ code cleaner.  However, boost is much more common and is a dependency anyhow.  If you believe that we should change to boost::signals only, I could agree.  I know Ullrich Köthe would agree as well, he suggested it already in the past.

**Comment by hmeine** [comment]
branch was merged, cf. #12
